services:
  go:
    build:
      context: ./
      dockerfile: docker/go.Dockerfile
    ports:
      - "8080:8080"

  db:
    image: mariadb:10.11
    volumes:
      - "mysql_var:/var/lib/mysql"
      - "./db:/docker-entrypoint-initdb.d"
    environment:
      MARIADB_USER: "admin"
      MARIADB_PASSWORD: "admin"
      MARIADB_DATABASE: "govsphp"
      MARIADB_ROOT_PASSWORD: "root"
      MARIADB_AUTO_UPGRADE: 1
      MARIADB_DISABLE_UPGRADE_BACKUP: 1

  nginx:
    build:
      context: ./
      dockerfile: docker/nginx.Dockerfile
    ports:
      - "8081:8081"

  php:
    build:
      context: ./
      dockerfile: docker/php.Dockerfile

volumes:
  mysql_var:
